"""CLI: solve an eikonal field with a chosen strategy on a chosen domain.

    python -m eikonax.scripts.solve --strategy fsm --domain se2 --scenario wall \
        --ny 41 --nx 41 --n-theta 16 --radius 3

    python -m eikonax.scripts.solve --strategy ntfields --domain se2 --scenario free \
        --epochs 2000 --batch-size 1000

`--strategy` picks the module (`eikonax.strategies`), `--domain` the domain
constructor (`eikonax.domains.DOMAINS`), `--scenario` the obstacle layout
(`eikonax.scenarios.SCENARIOS`). Every other flag is generated by
introspecting those callables' signatures (`eikonax.config`), so
`--strategy ntfields --help` and `--strategy fsm --help` show different
options. Mirrors `dynamic-hierarchy`'s `scripts/train.py`.
"""

from __future__ import annotations

import argparse
import sys

import numpy as np

from ..config import add_function_args
from ..domains import DOMAINS
from ..scenarios import SCENARIOS
from ..strategies import STRATEGIES


def _save(strategy: str, result, domain, out: str) -> None:
    if strategy == "fsm":
        np.savez(out, field=np.asarray(result))
        return
    # ntfields: `result` is a Model -- evaluate it on the domain's grid from
    # the centre source so the output is directly comparable to an fsm field.
    grid_shape = domain.grid_shape
    if grid_shape is None:
        raise SystemExit("ntfields output needs a domain with a grid_shape (e.g. --domain se2)")
    centre = np.asarray(domain.from_normalized(np.zeros((1, domain.dim))))[0]
    np.savez(out, field=np.asarray(result.field(centre, grid_shape)))


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    top = argparse.ArgumentParser(prog="eikonax.scripts.solve", add_help=False)
    top.add_argument("--strategy", required=True, choices=sorted(STRATEGIES))
    top.add_argument("--domain", default="se2", choices=sorted(DOMAINS))
    top.add_argument("--scenario", default="free", choices=sorted(SCENARIOS))
    top.add_argument("--out", default=None, help="output .npz path (default: eikonax-<strategy>.npz)")
    top.add_argument("-h", "--help", action="store_true")
    main_args, remaining = top.parse_known_args(argv)

    strat = STRATEGIES[main_args.strategy]
    domain_ctor = DOMAINS[main_args.domain]
    scenario_factory = SCENARIOS[main_args.scenario]

    # One parser for all three callables -- their flag names do not collide,
    # and a single parse avoids argparse mis-handling interspersed unknowns
    # across chained parsers (a real problem with nargs='+' options).
    parser = argparse.ArgumentParser(prog=top.prog, add_help=False)
    strat_names = add_function_args(parser, strat.solve)
    domain_names = add_function_args(parser, domain_ctor)
    scenario_names = add_function_args(parser, scenario_factory)

    if main_args.help:
        top.print_help()
        print(f"\n{main_args.strategy}/{main_args.domain}/{main_args.scenario} options:")
        parser.print_help()
        return 0

    args = parser.parse_args(remaining)
    pick = lambda names: {n: getattr(args, n) for n in names}

    speed_fn = scenario_factory(**pick(scenario_names))
    domain = domain_ctor(speed_fn, **pick(domain_names))

    def progress_fn(step, metrics):
        print(f"[{main_args.strategy}] {step}: {metrics}", flush=True)

    result = strat.solve(domain, progress_fn=progress_fn, **pick(strat_names))

    out = main_args.out or f"eikonax-{main_args.strategy}.npz"
    _save(main_args.strategy, result, domain, out)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
